### ISSUE TITLE
Interferes with navigation remaps

### ISSUE THREAD

**Issue by marcopolo4k** [dahu/SearchParty#14]
Love this plugin functionality! Just in case it's still supported:

I use these mappings found [here](https://stackoverflow.com/questions/9047107/navigating-between-vim-windows-in-an-alternative-way), and believe they're kind of common:
```
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
```

If I PlugInstall `Plug dahu/SearchParty` and reopen vim (8.0.1763, I think I saw on v9 as well), instead of switching window panes, these shortcuts just make the cursor blink; it does not switch.

I just tried another set found [here](https://stackoverflow.com/questions/6053301/easier-way-to-navigate-between-vim-split-panes), and had the same issue.

**Comment by dahu** [comment]
I don't think it's SearchParty that is preventing those maps (either form) from working. I tested by putting those maps in my vimrc with SearchParty in my plugin set and they worked fine (with the exception of <c-l> for reasons I'll talk about below.) Remove the <c-j> et al set of maps and try a fresh restart of vim and type   `:verbose map <c-j>`   to see if it tells you where an interfering mapping is coming from. Ultimately, you will be able to locate the reason those maps aren't working and then you'll be free to create them to navigate windows. However, you will have trouble with <c-l> because that is vim's built-in way of clearing the current search highlight, and SearchParty hooks into that for extra highlight clearing that it sets up. If you want to use <c-l> (which makes sense give the rest of the hjk you want to map), then you should re-map SearchParty's <c-l> to something else. To do this, you should harness SP's   `:help SearchParty-user-maps`   functionality. You'll need to locate that file (it should be in the sample dir that SP is installed) and ensure that you have  `let g:searchparty_load_user_maps = 1`   in your vimrc. 

Change the line that maps <c-l> to something like this:

    nnoremap <silent> <leader>l    <c-l><Plug>SearchPartyHighlightClear

You need to change the existing `nmap` to a `nnoremap` so that your new window jumping `<c-l>` isn't accidentally triggered whenever you use your new SearchParty user-map `<leader>l` to clear highlights.

**Comment by marcopolo4k** [comment]
Thank you that was it!  

So I have to edit ~/.vim/plugged/SearchParty/searchparty_user_maps.vim on every system I use this on?

I guess I have a feature request: Make this a variable so I don't have to edit files when auto-installing.  Or actually maybe I'm misunderstanding:

> all of the default maps shown below can be overridden using the <Plug> maps given.

Is this saying there's a way to override without editing the searchparty_user_maps.vim file?

**Comment by dahu** [comment]
If you're creating a new (unique to SearchParty's set of user-maps) key combination (e.g.` <leader>l`), then you can just define that in your vimrc as we did above. If you were planning to re-map an existing SP key mapping then you'd have to either use the SP provided user-maps file (everywhere you install) or use the `:help after` or `:help autocmd` facilities to override the plugin defaults. But in your case, you should be able to just stick that line in your vimrc and you're good to go.

BTW, I didn't realise that all of the `<c-l>` in my first message were going to be gobbled by github, so that message reads very poorly, sorry.

**Comment by marcopolo4k** [comment]
Ok, I'm happy to close this issue, thank you very much!

Oh, just to be clear, I still kind of wish there was a variable to do it - [here's a PR what I mean](https://github.com/dahu/SearchParty/pull/15/files).  The code is ugly, so I understand if you don't want to do it, no problem :)

**Comment by dahu** [comment]
Sorry, @marcopolo4k , I got sick and busy and couldn't spend any time on this issue until now.
I made some changes to the plugin code to check for any existing mappings to the <Plug> points that SearchParty provides, and if there is an existing map (defined in your vimrc, for example), then the startup code will not create the corresponding default user-map for that <Plug> from the user-maps file. So, for example, if you create a map from <leader>l to the <Plug>SearchPartyHighlightClear in your vimrc, the new startup code will NOT create a map from <c-l> to the same <Plug> point. This will leave <c-l> alone (and if you've already mapped it in your vimrc to navigate windows then it won't override it).

I would appreciate you having a play with this version to see if it solves the problem you were having. I understand if you've moved past this now to other issues. 

The new code is currently in a feature branch called feature-14-user-maps. If you test the code and you're not happy with it, I'll endeavour to work on it further. If I haven't heard anything after a while, I'll merge the changes back in to master.
